version: '3.8'

services:
  api:
    build: .
    ports:
      - "8001:8000"
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql://chess_user:chess_password@db:5432/chess_pgn_analyzer
    volumes:
      - ./src:/app/src
      - ./utils:/app/utils
    networks:
      - chess_network
    depends_on:
      - db

  db:
    image: postgres:16.4-alpine3.20
    container_name: chess_pgn_analyzer_db
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: chess_pgn_analyzer
      POSTGRES_USER: chess_user
      POSTGRES_PASSWORD: chess_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chess_network
    # Remove the ports section to prevent external access

  localtunnel-client:
    image: node:alpine
    command: >
      sh -c "
        echo 'Installing localtunnel...' &&
        npm install -g localtunnel &&
        echo 'Starting tunnel...' &&
        DEBUG=* lt --host http://lt.tadeasfort.cz:4000 --port 8000 --subdomain chess-api --local-host api --print-requests --allow-invalid-cert"
    environment:
      - DEBUG=localtunnel*
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - api
    networks:
      - chess_network

networks:
  chess_network:
    driver: bridge

volumes:
  postgres_data:
