services:
  db:
    image: postgres:16.4-alpine3.20
    container_name: chess_pgn_analyzer_db
    environment:
      POSTGRES_DB: chess_pgn_analyzer
      POSTGRES_USER: chess_user
      POSTGRES_PASSWORD: chess_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

