"""stockfish move analysis

Revision ID: f7642ec46928
Revises: 724962f0ad4d
Create Date: 2024-09-16 23:19:39.342607

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f7642ec46928"
down_revision: Union[str, None] = "724962f0ad4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game",
        sa.Column(
            "moves_analyzed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column("game", sa.Column("move_analysis", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "move_analysis")
    op.drop_column("game", "moves_analyzed")
    # ### end Alembic commands ###
